### ISSUE TITLE
feat: Solving week 9 assignment

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS#15]
## What is this issue? 🚀
Solve assignment of week 9, with using skeleton python file

## TODO 🏃‍♀️
- [x] Complete skeleton python code
- [x] Create image file of accuracy of my model
- [x] Try to get the best accuracy score as much as I can

**Comment by YohanIm00** [comment]
Done!
