### ISSUE TITLE
feat: Solving week 10 assignment

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS#17]
## What is this issue? 🚀
Solve assignment of week 10, with using skeleton python file

## TODO 🏃‍♀️
- [x] Run skeleton source code
- [x] Run Google Colab with the same code
- [x] Take the screen shot of it

**Comment by YohanIm00** [comment]
Done!
