### ISSUE TITLE
feat: Solving week 4 assignment

### ISSUE THREAD

**Issue by YohanIm00** [YohanIm00/OSS#5]
## What is this issue? 🚀
Solve assignment of week 4, with using skeleton python file

## TODO 🏃‍♀️
- [ ] Complete skeleton python file
- [x] Explain game concepts with 'turtle_runaway.md' file
- [ ] Add trivial stuffs after completing mandatory requirements

**Comment by YohanIm00** [comment]
Although it is imcomplete, I should merge this first for another assignment.
